---

- name: Install ProxySQL from repository
  package:
    name: "{{ proxysql_pkgs }}"
    state: present
    update_cache: yes
#    update_cache: "{{ omit if ((ansible_pkg_mgr == 'dnf') and (ansible_version is version('2.7', '<'))) else 'yes' }}"
  delay: 10
  register: result
  retries: 3
  until: result is succeeded
  when: >
        proxysql_use_official_repo or
        proxysql_use_percona_repo

- name: Install ProxySQL from DEB package
  apt:
    deb: "{{ proxysql_pkg_url }}"
    state: present
  delay: 10
  register: result
  retries: 3
  until: result is succeeded
  when: >
        (not proxysql_use_official_repo) and
        (not proxysql_use_percona_repo) and
        (ansible_os_family == "Debian")

- name: Install ProxySQL from YUM package
  yum:
    name: "{{ proxysql_pkg_url }}"
    state: present
  delay: 10
  register: result
  retries: 3
  until: result is succeeded
  when: >
        (not proxysql_use_official_repo) and
        (not proxysql_use_percona_repo) and
        (ansible_os_family == "RedHat")
