---
- name: Add proxysql Repository
  yum_repository:
    name: proxysql
    file: proxysql
    description: ProxySQL YUM repository
    baseurl: https://repo.proxysql.com/ProxySQL/proxysql-2.2.x/centos/$releasever
    gpgkey: https://repo.proxysql.com/ProxySQL/repo_pub_key
    state: present
