- name: Setup cluster
  hosts: all
  tasks:
    - name: "Include httpd installation setup"
      include_role:
        name: "webapp"
      when: inventory_hostname == "node1"

    - name: "Include mysql installation setup"
      include_role:
        name: "mysql"
      when: inventory_hostname == "node3" or inventory_hostname == "node4"

    - name: "Include proxysql installation setup"
      include_role:
        name: "proxysql" 
      when: inventory_hostname == "node2"
