all:
  hosts:
    node1:
      ansible_host: 10.10.0.31
      ip: 10.10.0.31
      access_ip: 10.10.0.31
    node2:
      ansible_host: 10.10.0.29
      ip: 10.10.0.29
      access_ip: 10.10.0.29
    node3:
      ansible_host: 10.10.0.107
      ip: 10.10.0.107
      access_ip: 10.10.0.107
    node4:
      ansible_host: 10.10.0.107
      ip: 10.10.0.107
      access_ip: 10.10.0.107
  children:
    mysql:
      hosts:
        node3:
        node4:
    proxysql:
      hosts:
        node2:
    webapp:
      hosts:
        node1:
