proxysql_version: 2.3.0
proxysql_backend_servers:
   mysql-srv1-hg1:
     comment: mysql-srv1-hg1
     hostgroup: 1
     hostname:  10.10.10.30
     login_host: "{{ proxysql_login_admin_host }}"
     login_password: "{{ proxysql_login_admin_password }}"
     login_port: "{{ proxysql_login_admin_port }}"
     login_user: "{{ proxysql_login_admin_user }}"
     max_connections: 1000
     max_replication_lag: 0
     status: ONLINE
     weight: 1
   mysql-srv1-hg2:
     comment: mysql-srv1-hg2
     hostgroup: 2
     hostname: 10.10.10.107
     login_host: "{{ proxysql_login_admin_host }}"
     login_password: "{{ proxysql_login_admin_password }}"
     login_port: "{{ proxysql_login_admin_port }}"
     login_user: "{{ proxysql_login_admin_user }}"
     max_connections: 1000
     max_replication_lag: 0
     status: ONLINE
     weight: 1

