---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: mysql_centos
    image: geerlingguy/docker-centos8-ansible
    command: /lib/systemd/systemd
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  - name: mysql_ubuntu
    image: geerlingguy/docker-ubuntu2004-ansible
    command: /lib/systemd/systemd
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  - name: webapp_ubuntu
    image: geerlingguy/docker-ubuntu2004-ansible
    command: /lib/systemd/systemd
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  - name: proxysql_centos
    image: geerlingguy/docker-centos8-ansible
    command: /lib/systemd/systemd
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true


provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
        children:
          mysql:
            hosts:
              mysql_centos:
              mysql_ubuntu:
          proxysql:
            hosts:
              proxysql_centos:
          webapp:
            hosts:
              webapp_ubuntu:
verifier:
  name: ansible
