proxysql_login_admin_host: 127.0.0.1
proxysql_login_admin_password: admin
proxysql_login_admin_port: 6032
proxysql_login_admin_user: admin




mysql_users:
  -  name: webapp
     password: 'Aa123456'
     priv: '*.*:ALL'

#mysql_users:
#        name: webapp 
#        host: localhost
#        password: Aa123456
#        priv: '*.*:ALL'
#        state: present
mysql_root_password_update: true
mysql_root_username: root
mysql_root_password: Aa123456
webapp_root: "/etc/default/webapp"
proxysql_hostname: proxysql_centos



mysql_databases:

       -  name: webapp_db
          encoding: utf8
          collation: utf8_general_ci
          replicate: 0
          state: present



proxysql_mysql_users:
   user1:
     active: 1
     backend: 1
     default_hostgroup: 1
     fast_forward: 0
     frontend: 1
     login_host: "{{ proxysql_login_admin_host }}"
     login_password: "{{ proxysql_login_admin_password }}"
     login_port: "{{ proxysql_login_admin_port }}"
     login_user: "{{ proxysql_login_admin_user }}"
     max_connections: 10000
     password: Aa123456
     transaction_persistent: 1
     username: webapp1
   user2:
     active: 1
     backend: 1
     default_hostgroup: 2
     fast_forward: 0
     frontend: 1
     login_host: "{{ proxysql_login_admin_host }}"
     login_password: "{{ proxysql_login_admin_password }}"
     login_port: "{{ proxysql_login_admin_port }}"
     login_user: "{{ proxysql_login_admin_user }}"
     max_connections: 1000
     password: Aa123456
     transaction_persistent: 1
     username: webapp2

proxysql_version: 2.3.0
proxysql_backend_servers:
   mysql-srv1-hg1:
     comment: mysql-srv1-hg1
     hostgroup: 1
     hostname: "10.10.0.30"
     login_host: "{{ proxysql_login_admin_host }}"
     login_password: "{{ proxysql_login_admin_password }}"
     login_port: "{{ proxysql_login_admin_port }}"
     login_user: "{{ proxysql_login_admin_user }}"
     max_connections: 1000
     max_replication_lag: 0
     status: ONLINE
     weight: 1
   mysql-srv1-hg2:
     comment: mysql-srv1-hg2
     hostgroup: 2
     hostname: "10.10.0.31"
     login_host: "{{ proxysql_login_admin_host }}"
     login_password: "{{ proxysql_login_admin_password }}"
     login_port: "{{ proxysql_login_admin_port }}"
     login_user: "{{ proxysql_login_admin_user }}"
     max_connections: 1000
     max_replication_lag: 0
     status: ONLINE
     weight: 1


mysql_users:
  -  name: webapp
     password: 'Aa123456'
     priv: '*.*:ALL'

